### ISSUE TITLE
Run only one scenario on ALOE test runner

### ISSUE THREAD

**Issue by maikvortx** [herbsjs/aloe#7]
**Is your feature request related to a problem? Please describe.**

Is not possible to run only one scenario when the test is running.

**Describe the solution you'd like**

Implement the `scenario.only` function to run only one scenario.

**Describe alternatives you've considered**

**Additional context**

Many test runners like mocha or jest have this function, which is very important to debug tests.

**Comment by dalssoft** [comment]
Here are my suggestions...

## Spec

This is the suggested code to run only one spec:

```js
const createUserSpec = spec.only({
```

There should have a visual indicator that the spec was marked as `only` when running `herbs spec`.

If many specs are marked as `only`, it should run all the `only` specs.

## Scenario

This is the suggested code to run only one scenario:

```js
const createUserSpec = spec({

    ...
  
    'Create a new user when it is valid': scenario.only({
```

There should have a visual indicator that the scenario was marked as `only` when running `herbs spec`.

If many scenarios are marked as `only`, it should run all the `only` scenarios.

## Given, When and Check

For `given`, `when` and `check` I don't see the need to have a `only` method.
