### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vitorgamer58** [herbsjs/aloe#9]
The documentation does not explain how the test function should be exported, nor the `herbs spec` command that is used to run the tests, nor does it explain whether herbarium is necessary or not to use Aloe.

**Comment by jhomarolo** [comment]
@vitorgamer58 I agree with you. The documentation need to be improved.

**Comment by dalssoft** [comment]
Fixed: https://github.com/herbsjs/herbsjs.github.io/commit/c91fb0d0e3ec09f58b078204ac72a80fa1b62547 and https://github.com/herbsjs/herbsjs.github.io/commit/a208453facf80e43d37296a3be0c38e8c5027fea
